# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: React APP CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

    - name: GitHub Organization User Activity Report
      id: analyze_user_activity
      uses: peter-murray/inactive-users-action@v1
      with:
        token: ${{ secrets.ORGANIZATION_AND_REPO_ACCESS_TOKEN }}
        organization: royality-travel-systems
        activity_days: 10
    - name: Save User Activity Report
      uses: actions/upload-artifact@v2
      with:
        name: reports
        path: |
          ${{ steps.analyze_user_activity.outputs.report_csv }}
